spring:
  application:
    name: gestao_vagas
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_vagas
    username: admin
    password: admin
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# server:
#   error:
#     include-message: never
#     include-binding-errors: never
#     include-stacktrace: never
#     include-exception: false
